- name: Installing RabbitMQ repository
  shell: curl https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm | sudo bash
  args:
    creates: /etc/yum.repos.d/rabbitmq_rabbitmq-server.repo

- name: Installing RabbitMQ packages
  yum: name={{ item }} state=latest
  with_items:
    - erlang
    - rabbitmq-server
  tags:
    - rabbitmq

- name: Starting RabbitMQ service
  service: name=rabbitmq-server enabled=yes state=started
  tags:
    - rabbitmq

- name: Creating RabbitMQ configuration file
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: Restart rabbitmq
  tags:
    - rabbitmq

- name: Enable RabbitMQ plugins
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  tags:
    - rabbitmq
