- name: Downloading RabbitMQ repository installation script
  get_url: url=https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm dest=/tmp/rabbit-mq-install.sh force=true
  tags:
    - rabbitmq

- name: Making RabbitMQ repository installation script executable
  file: path=/tmp/rabbit-mq-install.sh mode=u+x
  tags:
    - rabbitmq

- name: Running RabbitMQ repository installation script
  shell: /tmp/rabbit-mq-install.sh
  args:
    creates: /etc/yum.repos.d/rabbitmq_rabbitmq-server.repo
  tags:
    - rabbitmq

- name: Delete RabbitMQ repository installation script
  file: path=/tmp/rabbit-mq-install.sh state=absent
  tags:
    - rabbitmq

- name: Installing RabbitMQ packages
  yum: name={{ item }} state=latest
  with_items:
    - erlang
    - rabbitmq-server
  tags:
    - rabbitmq

- name: Starting RabbitMQ service
  service: name=rabbitmq-server enabled=yes state=started
  tags:
    - rabbitmq

- name: Creating RabbitMQ configuration file
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: Restart rabbitmq
  tags:
    - rabbitmq

- name: Enable RabbitMQ plugins
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  tags:
    - rabbitmq

- name: Setting up firewalld for RabbitMQ
  firewalld: port={{ item }}/tcp permanent=true immediate=true state=enabled zone=public
  with_items:
    - 5672
    - 15672
  when: env_name == 'development'
  tags:
    - rabbitmq
