---
- name: Installing RabbitMQ GPG Keys
  rpm_key: key={{ item }} state=present
  with_items:
    - https://packagecloud.io/gpg.key
    - http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
  tags:
    - rabbitmq

- name: Installing RabbitMQ repository file
  template: src=rabbitmq_rabbitmq-server.repo.j2 dest=/etc/yum.repos.d/rabbitmq_rabbitmq-server.repo
  tags:
    - rabbitmq

- name: Installing RabbitMQ packages
  yum: name={{ item }} state=latest
  with_items:
    - erlang
    - rabbitmq-server
  tags:
    - rabbitmq

- name: Starting RabbitMQ service
  service: name=rabbitmq-server enabled=yes state=started
  tags:
    - rabbitmq

- name: Creating RabbitMQ configuration file
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config
  notify: restart rabbitmq
  tags:
    - rabbitmq

- name: Enable RabbitMQ plugins
  rabbitmq_plugin: names=rabbitmq_management state=enabled
  tags:
    - rabbitmq
