---
- name: Installing Postgres Yum repository package
  yum: name=http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm state=present
  tags:
    - postgres

- name: Installing Postgres Yum packages
  yum: name={{ item }} state=latest
  with_items:
    - postgresql94-server
    - postgresql94-contrib
    - python-psycopg2
  tags:
    - postgres

- name: Initializing Postgres database
  command: /usr/pgsql-9.4/bin/postgresql94-setup initdb
  args:
    creates: /var/lib/pgsql/9.4/data/PG_VERSION
  tags:
    - postgres

- name: Copying Postgres configuration files
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: postgresql.conf.j2, dest: /var/lib/pgsql/9.4/data/postgresql.conf }
    - { src: pg_hba.conf.j2, dest: /var/lib/pgsql/9.4/data/pg_hba.conf }
  notify:
    - Restart postgres
  tags:
    - postgres

- name: Starting Postgres service
  service: name=postgresql-9.4 state=started enabled=yes
  tags:
    - postgres

- name: Creating Postgres database user
  postgresql_user: name={{ user }} password={{ password }}
  sudo: yes
  sudo_user: postgres
  tags:
    - postgres

- name: Creating Postgres database
  postgresql_db: name={{ database }} owner={{ user }}
  sudo: yes
  sudo_user: postgres
  tags:
    - postgres

- name: Installing Postgres database extensions
  postgresql_ext: name={{ item }} db={{ database }}
  sudo: yes
  sudo_user: postgres
  with_items: "{{ extensions }}"
  tags:
    - postgres
