---

#
# This project is maintained by:
#  _    ____          ___      __               ____             __
# | |  / / /___ _____/ (_)____/ /___ __   __   / __ \____ ______/ /________  ___________  __  ____  __
# | | / / / __ `/ __  / / ___/ / __ `/ | / /  / /_/ / __ `/ ___/ __/ ___/ / / / ___/ __ \/ / / / / / /
# | |/ / / /_/ / /_/ / (__  ) / /_/ /| |/ /  / _, _/ /_/ (__  ) /_/ /  / /_/ (__  ) / / / /_/ / /_/ /
# |___/_/\__,_/\__,_/_/____/_/\__,_/ |___/  /_/ |_|\__,_/____/\__/_/   \__,_/____/_/ /_/\__, /\__, /
#                                                                                   /____//____/
#
# Email: FractalizeR@yandex.ru, vladislav.rastrusny@gmail.com
# http://www.fractalizer.ru
#
# This work is licensed under the Apache 2.0
# United States License. To view a copy of this license, visit
# http://www.apache.org/licenses/LICENSE-2.0
# or send a letter to The Apache Software Foundation Dept. 9660 Los Angeles, CA 90084-9660 U.S.A.
#

- name: Installing PHP XDebug, PHP-Cli, Node and NPM for developers
  yum: name={{ item }} state=latest
  with_items:
    - php-cli
    - php-pecl-xdebug
    - nodejs
    - npm

- name: Installing Composer
  shell: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/bin --filename=composer
  args:
    creates: /usr/bin/composer

- name: Create xdebug logs directory
  file: dest=/var/log/xdebug owner={{ http_user }} group={{ http_user }} state=directory recurse=yes

- name: Copying xdebug configuration files
  template: src=xdebug.conf.j2 dest=/etc/php.d/15-xdebug.ini
  notify: Restart php-fpm

- name: Adding website url to hosts IPv4
  lineinfile: dest=/etc/hosts line="127.0.0.1   {{ item }}"
  with_items: domains

- name: Adding website url to hosts IPv6
  lineinfile: dest=/etc/hosts line="::1         {{ item }}"
  with_items: domains