---
- name: Importing Nginx and PHP rpm keys
  rpm_key: key={{ item }}
  with_items:
    - http://rpms.famillecollet.com/RPM-GPG-KEY-remi
    - http://nginx.org/keys/nginx_signing.key

- name: Installing Nginx and PHP repositories
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: nginx.repo.j2, dest: /etc/yum.repos.d/nginx.repo }
    - { src: php.remi.repo.j2, dest: /etc/yum.repos.d/remi.repo }

- name: Installing PHP and Nginx
  yum: name={{ item }} state=latest
  with_items:
    - nginx
    - php-fpm
    - php-gd
    - php-devel
    - php-mbstring
    - php-mcrypt
    - php-opcache
    - php-pdo
    - php-pgsql
    - php-intl
    - php-bcmath

- name: Setting permissions for nginx cache folder
  file: dest=/var/lib/nginx owner={{ http_user }} group={{ http_user }} state=directory recurse=yes

- name: Setting permissions for php sessions folder
  file: dest=/var/lib/php owner={{ http_user }} group={{ http_user }} state=directory recurse=yes

- name: Deleting default nginx configuration files
  file: path={{ item }} state=absent
  with_items:
    - /etc/nginx/conf.d/default.conf
    - /etc/nginx/conf.d/example_ssl.conf
  notify:
    - Restart nginx

- name: Deleting default php-fpm configuration files
  file: path={{ item }} state=absent
  with_items:
    - /etc/php-fpm.d/www.conf
  notify:
    - Restart php-fpm

- name: Copying nginx configuration files
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: nginx.conf.j2, dest: /etc/nginx.conf }
    - { src: site.nginx.conf.j2, dest: "/etc/nginx/conf.d/{{ site_id }}.conf" }
  notify:
    - Restart nginx

- name: Copying PHP configuration
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: php.ini.j2, dest: /etc/php.ini }
    - { src: php-fpm.conf.j2, dest: /etc/php-fpm.conf }
    - { src: site.php-fpm.conf.j2, dest: "/etc/php-fpm.d/{{ site_id }}.conf" }
  notify:
    - Restart php-fpm

- name: Starting PHP service
  service: name=php-fpm state=started enabled=yes

- name: Starting Nginx service
  service: name=nginx state=started enabled=yes

- include: development.yml
  when: env_name == 'development'